#! /usr/bin/env php
<?php
require 'vendor/autoload.php';

use Symfony\Component\Console\Application;
use Woger\Command\DeployKanban;
use Woger\Command\MakeSql;
use Woger\Command\SshKanban;

const ESB_PATH = '/var/www';

$esb = new Application("ESB command tool", "1.0");
$commands = array(
    new MakeSql(),
    new DeployKanban(),
    new SshKanban(),
);

$esb->addCommands($commands);
$esb->run();


